# Generated by Django 2.2.6 on 2019-10-26 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20191026_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='grade',
            field=models.IntegerField(default=0, help_text='Enter the tasks grade'),
        ),
    ]
