# Generated by Django 2.2.6 on 2019-10-26 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20191026_0640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='grade',
        ),
    ]
