# Generated by Django 2.2.6 on 2019-10-26 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_task_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='grade',
            field=models.IntegerField(default=0, help_text='Enter the tasks grade'),
        ),
    ]
