# Generated by Django 2.2.6 on 2019-10-26 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_task_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='subject',
        ),
        migrations.AddField(
            model_name='task',
            name='subject',
            field=models.ForeignKey(help_text='Select subject for this tasks', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Subject'),
        ),
    ]
