# Generated by Django 2.2.6 on 2019-10-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20191026_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='subject',
        ),
        migrations.AddField(
            model_name='task',
            name='subject',
            field=models.ManyToManyField(help_text='Select subject for this tasks', to='catalog.Subject'),
        ),
    ]
